### ISSUE TITLE
Unwanted hidden input on check_box helper with bootstrap_form_tag

### ISSUE THREAD

**Issue by Soullivaneuh** [bootstrap-ruby/rails-bootstrap-forms#215]
With the following template:

``` haml
= bootstrap_form_tag url: admin_namespaces_projects_path, method: :get do |f|
  = f.form_group label: { text: 'Activity' } do
    = f.check_box :with_push, name: :with_push, label: 'Projects with push events', checked: params[:with_push]
```

We got this html result for the `with_push` element:

``` html
<div class="checkbox">
  <label for="_with_push">
    <input name="with_push" type="hidden" value="0">
    <input id="_with_push" name="with_push" type="checkbox" value="1">
    Projects with push events
  </label>
</div>
```

The hidden field is unwanted and produce this following url parameters:

```
&with_push=0&with_push=1
```

That not works.

Is that an issue? How to disable it?

Thanks.

**Comment by Soullivaneuh** [comment]
More weird:

```haml
= f.form_group label: { text: 'Visibility level' } do
  - Project.visibility_levels.each do |label, level|
    = f.check_box :visibility_levels, name: 'visibility_levels[]', label: label, value: level, checked: params[:visibility_levels].present? && params[:visibility_levels].include?(level.to_s)
```

Produce:

```html
<div class="form-group">
  <label class="control-label">
    Visibility level
  </label>
  <div class="checkbox">
    <label for="_visibility_levels">
      <input name="visibility_levels[]" type="hidden" value="0">
      <input id="_visibility_levels" name="visibility_levels[]" type="checkbox" value="1">
      Private
    </label>
  </div>
  <div class="checkbox">
    <label for="_visibility_levels">
      <input name="visibility_levels[]" type="hidden" value="0">
      <input id="_visibility_levels" name="visibility_levels[]" type="checkbox" value="1">
      Internal
    </label>
  </div>
  <div class="checkbox">
    <label for="_visibility_levels">
      <input name="visibility_levels[]" type="hidden" value="0">
      <input id="_visibility_levels" name="visibility_levels[]" type="checkbox" value="1">
      Public
    </label>
  </div>
</div>
```

**Comment by datWav** [comment]
The hidden input is needed. If you remove the hidden field and uncheck the checkbox the value are still true after the save. 
Please check: http://stackoverflow.com/questions/11550941/why-does-the-check-box-form-helper-generate-two-checkboxes-one-hidden

**Comment by hut8** [comment]
This causes issues in collections. I have a filter which has some checkboxes. If none are checked, it should display every record. But since `model[my_filter]=''` ends up in the query string, the SQL generated by passing `params[:model]` to `where` ends up matching nothing.

In Rails 4 with `form_for`, there's a way to disable this by passing `include_hidden: false` as an option to the `collection_check_boxes` method (in `actionview/lib/action_view/helpers/tags/collection_check_boxes.rb`). The main reason I'm posting this is because it seems like that doesn't work with `bootstrap_form_for`. If I change my code to just use `form_for`, with the option I mentioned passed to the `collection_check_boxes` method, everything works.

**Comment by sinscary** [comment]
@hut8 Nope, this is not working for me. I am still getting hidden field, even after using `include_hidden: false`

**Comment by krsyoung** [comment]
I'm having a hard time finding a clean way to work around this (Google is not giving any answers!).  The issue seems to be with: https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/0fba8444cecdccec3c662de3988cc2d35c3fe2e5/lib/bootstrap_form/form_builder.rb#L168-L174

The `hidden_field` is always appended (regardless of any `include_hidden: false`) setting.  A (ugly) workaround could be something like:

```
    def collection_check_boxes_with_bootstrap(*args)
      include_hidden = true
      html = inputs_collection(*args) do |name, value, options|
        options[:multiple] = true
         if options.key?(:include_hidden) && options[:include_hidden] == false
           include_hidden = false
         end
        check_box(name, options, value, nil)
      end
      if include_hidden
        html = hidden_field(args.first,{value: "", multiple: true}).concat(html)
      end
      html
    end
```

This then ensures the `include_hidden: false` is respected.  Would love to find a good example to work around this without touching `include_hidden` at all.

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.

**Comment by a5-stable** [comment]
Hi, Is there any progress on this?
I'm in trouble with unwanted hidden input.

**Comment by donv** [comment]
I looked at the PR, and it looks good to me.  However there is a problem with the "danger" linting, and I am not familiar with it.
