### ISSUE TITLE
collection_check_boxes - set custom class

### ISSUE THREAD

**Issue by mike927** [bootstrap-ruby/rails-bootstrap-forms#256]
I encounterded an issue. I use "collection_check_boxes" helper and I can't set custom class for checkbox label or checkbox input. I read the documentation and I couldn't find how to do it.

**Comment by am17torres** [comment]
I just ran into issues with the collection_check_boxes too. Turns out this version doesn't support passing in a block. Problem can be seen [here](https://github.com/bootstrap-ruby/rails-bootstrap-forms/blob/master/lib/bootstrap_form/form_builder.rb#L156). 

I tried piping the `&block` along to `check_box_with_bootstrap` however there are some logic errors in there such as creating a checkbox in addition to w/e is in the block (so you ended up with double checkboxes. Easy enough to fix...

Then I got to this part and thats where I gave up: 

> The argument passed to the block is a special kind of builder for this collection, which has the ability to generate the label and check box for the current item in the collection, with proper text and value. Using it, you can change the label and check box display order or even use the label as wrapper, as in the example above.
> 
> The builder methods label and check_box also accept extra html options:
> 
> collection_check_boxes(:post, :author_ids, Author.all, :id, :name_with_initial) do |b|
>   b.label(class: "check_box") { b.check_box(class: "check_box") }
> end
>
> There are also three special methods available: object, text and value, which are the current item being rendered, its text and value methods, respectively. You can use them like this:
> 
> collection_check_boxes(:post, :author_ids, Author.all, :id, :name_with_initial) do |b|
>    b.label(:"data-value" => b.value) { b.check_box + b.text }
> end

Maybe somebody more ambitious than I can tackle this problem.

**Comment by starrychloe** [comment]
This works with plain Rails and Bootstrap 4, no gem required. [`collection_check_boxes`](http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-collection_check_boxes) is a plain Rails method.

```
  .form-group
    =f.label :industry_interest
    %br
    =f.collection_check_boxes :industry_interest, Industry.all, :id, :name do |cb|
      =cb.check_box 
      =cb.label
      %br
```

or 

```
  .form-group
    =f.label :industry_interest
    =f.collection_check_boxes :industry_interest, Industry.all, :id, :name do |cb|
      .form-check
        =cb.label class: 'form-check-label' do
          =cb.check_box class: 'form-check-input'
          =cb.text 
```

They look identical. 

https://v4-alpha.getbootstrap.com/components/forms/#checkboxes-and-radios

**Comment by fanjieqi** [comment]
+1

**Comment by mattbrictson** [comment]
Cleaning up old unanswered issues. If this question is still relevant, please reopen.
