### ISSUE TITLE
Support for Bootstrap 4

### ISSUE THREAD

**Issue by stujo** [bootstrap-ruby/rails-bootstrap-forms#268]
Hi I'm working on support for bootstrap 4 for a project here:

https://github.com/stujo/rails-bootstrap-forms/tree/support-bootstrap-4

Please let me know if I can be of any assistance

Cheers
Stu

**Comment by gcrofils** [comment]
Hi. I m starting to use Bootstrap 4 for a new project.
What have you done so far ?
I would be very happy to contribute.

**Comment by stujo** [comment]
Cool, really the only change I've had to make so far was to change has-error to has-danger

https://github.com/stujo/rails-bootstrap-forms/commits/support-bootstrap-4

It might be possible to keep has-error and use scss instead

Happy to work together

**Comment by mattbrictson** [comment]
I'm assuming supporting Bootstrap 4 will break backwards compatibility with Bootstrap 3, since the class names are different. Am I correct?

If so, that means we'll need a strategy for how to support both v3 and v4 with the bootstrap_rails gem. I'm open to suggestions! Some ideas:

* Have v3 and v4 "modes" within the gem that can be switched using e.g. a Rails initializer.
* Branch the gem and release two different versions: the current 2.x series will continue support Bootstrap v3, and a new 3.x (or better, 4.x) series will support Bootstrap v4.

I guess it depends on how much different v3 and v4 are. Thoughts?

**Comment by stujo** [comment]
@mattbrictson Looks like there are some differences, I'd lean towards having a version of the library which 'does one thing well' - in this case 'supports v4'. 

If it turns out that a mode switch is easy then adding that later could be an option and the changes could be merged into upstream

If not then the library with v4 support could be renamed to something like rails-bootstrap-v4-forms

Thoughts?

**Comment by mattbrictson** [comment]
If there are major differences in the markup that is generated, then I agree we should package it as a completely new gem.

**Comment by stujo** [comment]
Great, let's see how it plays out!

**Comment by jonathantribouharet** [comment]
Currently in rails-bootstrap-forms, the submit button in the form use `btn-default`.

In bootstrap 4, `btn-default` is renamed by `btn-secondary`
Here the link suggesting to rename according to the migration:
http://v4-alpha.getbootstrap.com/migration/#buttons

But if you look at the form exemple, they replace btn-default by btn-primary, which seems more logic:
http://v4-alpha.getbootstrap.com/components/forms/

Thankfully, there is the method `primary` for now.

**Comment by desheikh** [comment]
Created a PR with a fairly complete list of changes for bootstrap v4 support #304. The changes themselves are fairly minor.
@mattbrictson Could we get a v4 branch up so that we can track changes/fixes centrally?

**Comment by mattbrictson** [comment]
@desheikh Good idea. I've created a `bootstrap-v4` branch.

**Comment by desheikh** [comment]
@mattbrictson Thanks! Switched the PR to point to the new branch.

**Comment by krsyoung** [comment]
I'm currently working off of bootstrap-v4 branch with the alpha6 release.  Has anybody here created a horizontal form (https://v4-alpha.getbootstrap.com/components/forms/#using-the-grid)?  I'm trying to figure out if it could be handled via the previous `layout: 'horizontal'` approach (removed in #304) or if we should just be avoiding the library in this case due to how generic the grid is?

**Comment by dan** [comment]
Where are things with this? Seems like there are still many form-related issues (e.g. radio and checkbox alignment, etc.).

**Comment by desheikh** [comment]
Hi @dan, are you using the bootstrap-v4 branch? If so, make sure you are using boostrap alpha 6 and file a ticket for any specific issues you are seeing.

**Comment by JohnSmall** [comment]
I've just added some upvotes on this thread. I've held off going to Bootstrap 4 because I need bootstrap_form to work with it. I'll take a look at the bootstrap-v4 branch. If I find any issues I'll try fixing them and raise a PR.

**Comment by kylefox** [comment]
I'd like to bump this now that the [Bootstrap 4 Beta](https://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/) has _finally_ been released 😎 🎉 

I've been using the `bootstrap-v4` and it's been pretty great so far 👍 but I see it's become a bit stale.

So, I'm just wondering what the status and plan (if any) for Bootstrap 4 is, and how we can help. Cheers!

**Comment by SaimonL** [comment]
I am using the branch "bootstrap-v4" and I love it. 
I started new rails 5.1.3 project and no problem. 

```ruby
gem 'jquery-rails' # This is removed in Rails 5.1.3 so you will need to add it back.
gem 'bootstrap', '4.0.0.alpha6'
gem 'bootstrap_form', git: 'https://github.com/bootstrap-ruby/rails-bootstrap-forms.git', branch: 'bootstrap-v4'
```

### Bootstrap
The version **~> 4.0.0.beta** just don't work right the coloring is dead and class name mismatch.
The version **4.0.0.alpha6** does work but has one global error on JavaScript console

```
Uncaught Error: Bootstrap tooltips require Tether (http://tether.io/)
  at tooltip.js?body=1:21
  at tooltip.js?body=1:622
(anonymous) @ tooltip.js?body=1:21
(anonymous) @ tooltip.js?body=1:622
```
Seemed to be only tooltip related.

**Comment by JohnSmall** [comment]
Is 'tether-rails' required for the BS-4 setup or is it just something you added because it's in your project?

**Comment by GBH** [comment]
Bootstrap 4 is in beta2 now. `bootstrap-v4` works but missing a bunch of stuff (like proper css classes for errors and stuff). Can we setup a project with TODOs to get this gem ready? Somewhere we can submit PRs against? Or even maybe shift master branch to v4 and put v3 on it's own branch? 

There's very little activity going on here.

**Comment by edwardmp** [comment]
@GBH 

I agree. Something I noticed that is broken with Bootstrap v4 beta 2:
`<%= f.submit %>` by default adds the `btn btn-default` classes. `btn-default` is no longer a thing, so we probably need to use `btn-primary`. See https://v4-alpha.getbootstrap.com/components/buttons/ for available classes.

**Comment by GBH** [comment]
I needed a dependency that I can define in gemspec, so I forked and released gem that works with Bootstrap 4: https://github.com/comfy/comfy-bootstrap-form, https://rubygems.org/gems/comfy_bootstrap_form Released as version 4.0.0.beta1 to match Bootstrap version.

It's just v4 branch merged into master with just one fix that adds `is-invalid` class on inputs so stuff gets red. 

Going forward, this is what I'd do:
* Drop support for Rails < 5.0 completely. You still can use older gems, but this will clean up version checks everywhere and remove crap like `style="margin:0;padding:0;display:inline"` that went away in Rails 4.2
* HTML markup is not correct in a lot of cases. Doesn't hurt, but not correct.
* Checkbox rendering is not producing proper html still.
* Fix tests to use heredoc instead of blobs of squished html. Impossible to see what's going on.

I can't wait for years until Bootstrap gets out of beta and this gem gets updated and published. So, feel free to use my gem in interim. (I'll merge and publish any PRs that fix stuff)

**Comment by mattbrictson** [comment]
Thanks for the suggestions, @GBH. I've just published a roadmap for the next version of bootstrap_form here: #361. It would be great if you could log issues or PRs for the problems you identified. I am trying to build momentum to getting a v4 gem published and would appreciate the help!

**Comment by mattbrictson** [comment]
Closing this thread in favor of moving the discussion here: #361.
