### ISSUE TITLE
check_box ignores help

### ISSUE THREAD

**Issue by lastobelus** [bootstrap-ruby/rails-bootstrap-forms#316]
```
<%= f.check_box :stuff, help: "Provides stuff" %>
```

does not render the help text.

**Comment by mattbrictson** [comment]
Yes, this is a bit tricky due to how check boxes are rendered by Bootstrap. To display help and error message for a check box you need to wrap it in a `form_group`, like this:

```erb
<%= f.form_group :stuff do %>
  <%= f.check_box :stuff, help: "Provides stuff" %>
<% end %>
```

This is already documented in the README, here: https://github.com/bootstrap-ruby/rails-bootstrap-forms#checkboxes-and-radios

**Comment by nodrog** [comment]
@mattbrictson 's answer is a bit wrong in that the help option needs to be on the form group not on the checkbox. But it is documented as he has stated.

**Comment by lcreid** [comment]
Thanks, @nodrog. We had a lot of challenges with the positioning of help and errors for Bootstrap 4, since it changed in significant ways. See #418, #419, #436, #448, #444, #454, etc. I think we have it right now, but if you're seeing wrong behaviour, please let us know how to reproduce the problem, and we'll look at it.
